// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Wheelchair_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean Boool;
        
        public Valve.VR.SteamVR_Action_Single Vec1;
        
        public Valve.VR.SteamVR_Action_Vector2 Vec2;
        
        public Valve.VR.SteamVR_Action_Vector3 Vec3;
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Skeleton Skelly;
    }
}
